/*
 * Copyright (c) 2016 CUBRID Corporation.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * - Neither the name of the <ORGANIZATION> nor the names of its contributors
 *   may be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 */

package cubrid.jdbc.lb.statement;

import static org.junit.Assert.*;

import cubrid.jdbc.driver.CUBRIDPreparedStatement;
import cubrid.jdbc.driver.CUBRIDStatement;
import cubrid.jdbc.lb.LbJDBCErrorCode;
import cubrid.jdbc.lb.LoadBalanceConnection;
import cubrid.jdbc.lb.config.TestConfigHelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.junit.Before;
import org.junit.Test;

public class LBPreparedStatementTest {

    private LoadBalanceConnection conn;

    @Before
    public void setUp() throws Exception {
        conn = new LoadBalanceConnection(TestConfigHelper.emptyConfig());
    }

    @Test
    public void assertPrepareStatementReturnsLBPreparedStatement() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        assertTrue(ps instanceof LBPreparedStatement);
        assertFalse(ps.isClosed());
    }

    @Test
    public void assertPrepareStatementRetainsSql() throws Exception {
        LBPreparedStatement ps =
                (LBPreparedStatement) conn.prepareStatement("SELECT id FROM t WHERE id = ?");
        assertEquals("SELECT id FROM t WHERE id = ?", ps.getSql());
        assertSame(conn, ps.getOwnerConn());
        assertNotNull(ps.getSessState());
        assertNotNull(ps.getParameterBinder());
    }

    @Test
    public void assertPrepareStatementDefaultResultSetProperties() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        assertEquals(ResultSet.TYPE_FORWARD_ONLY, ps.getResultSetType());
        assertEquals(ResultSet.CONCUR_READ_ONLY, ps.getResultSetConcurrency());
        assertEquals(ResultSet.HOLD_CURSORS_OVER_COMMIT, ps.getResultSetHoldability());
    }

    @Test
    public void assertPrepareStatementWithTypeAndConcurrency() throws Exception {
        PreparedStatement ps =
                conn.prepareStatement(
                        "SELECT 1", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        assertEquals(ResultSet.TYPE_SCROLL_INSENSITIVE, ps.getResultSetType());
        assertEquals(ResultSet.CONCUR_UPDATABLE, ps.getResultSetConcurrency());
    }

    @Test
    public void assertPrepareStatementWithThreeArgs() throws Exception {
        PreparedStatement ps =
                conn.prepareStatement(
                        "SELECT 1",
                        ResultSet.TYPE_SCROLL_SENSITIVE,
                        ResultSet.CONCUR_UPDATABLE,
                        ResultSet.CLOSE_CURSORS_AT_COMMIT);
        assertEquals(ResultSet.TYPE_SCROLL_SENSITIVE, ps.getResultSetType());
        assertEquals(ResultSet.CONCUR_UPDATABLE, ps.getResultSetConcurrency());
        assertEquals(ResultSet.CLOSE_CURSORS_AT_COMMIT, ps.getResultSetHoldability());
    }

    @Test
    public void assertPrepareStatementAutoGeneratedKeys() throws Exception {
        PreparedStatement ps =
                conn.prepareStatement(
                        "INSERT INTO t VALUES(1)", java.sql.Statement.RETURN_GENERATED_KEYS);
        assertTrue(ps instanceof LBPreparedStatement);
        assertEquals("INSERT INTO t VALUES(1)", ((LBPreparedStatement) ps).getSql());
    }

    @Test
    public void assertPrepareStatementColumnIndexes() throws Exception {
        PreparedStatement ps = conn.prepareStatement("INSERT INTO t VALUES(1)", new int[] {1});
        assertTrue(ps instanceof LBPreparedStatement);
    }

    @Test
    public void assertPrepareStatementColumnNames() throws Exception {
        PreparedStatement ps =
                conn.prepareStatement("INSERT INTO t VALUES(1)", new String[] {"id"});
        assertTrue(ps instanceof LBPreparedStatement);
    }

    @Test
    public void assertGetConnectionReturnsParent() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        Connection parent = ps.getConnection();
        assertSame(conn, parent);
    }

    @Test
    public void assertPreparedStatementCloseAndIsClosed() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        assertFalse(ps.isClosed());
        ps.close();
        assertTrue(ps.isClosed());
    }

    @Test
    public void assertClosedPreparedStatementThrowsSQLException() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        ps.close();
        try {
            ps.executeQuery();
            fail("Expected SQLException on closed statement");
        } catch (SQLException e) {
            assertTrue(e.getMessage().contains("closed"));
        }
    }

    @Test
    public void assertExecuteQueryOnUnboundConnectionThrows() throws Exception {
        try {
            conn.prepareStatement("SELECT 1").executeQuery();
            fail("expected SQLException: this connection was never bound to a session");
        } catch (SQLException expected) {
            assertEquals(LbJDBCErrorCode.lb_internal_state, expected.getErrorCode());
        }
    }

    @Test
    public void assertExecuteUpdateOnUnboundConnectionThrows() throws Exception {
        try {
            conn.prepareStatement("INSERT INTO t VALUES(1)").executeUpdate();
            fail("expected SQLException: this connection was never bound to a session");
        } catch (SQLException expected) {
            assertEquals(LbJDBCErrorCode.lb_internal_state, expected.getErrorCode());
        }
    }

    @Test
    public void assertExecuteOnUnboundConnectionThrows() throws Exception {
        try {
            conn.prepareStatement("SELECT 1").execute();
            fail("expected SQLException: this connection was never bound to a session");
        } catch (SQLException expected) {
            assertEquals(LbJDBCErrorCode.lb_internal_state, expected.getErrorCode());
        }
    }

    @Test
    public void assertClearParametersWhenOpen() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT ?");
        ps.clearParameters();
    }

    @Test
    public void assertSetIntDoesNotThrow() throws Exception {
        LBPreparedStatement ps = (LBPreparedStatement) conn.prepareStatement("SELECT ?");
        ps.setInt(1, 42);
        assertEquals(1, ps.getParameterBinder().size());
    }

    @Test
    public void assertSetStringDoesNotThrow() throws Exception {
        LBPreparedStatement ps = (LBPreparedStatement) conn.prepareStatement("SELECT ?");
        ps.setString(1, "hello");
        assertEquals(1, ps.getParameterBinder().size());
    }

    @Test
    public void assertSetNullDoesNotThrow() throws Exception {
        LBPreparedStatement ps = (LBPreparedStatement) conn.prepareStatement("SELECT ?");
        ps.setNull(1, java.sql.Types.VARCHAR);
        assertEquals(1, ps.getParameterBinder().size());
    }

    @Test
    public void assertClearParametersClearsBinderOperations() throws Exception {
        LBPreparedStatement ps = (LBPreparedStatement) conn.prepareStatement("SELECT ?");
        ps.setInt(1, 7);
        ps.setString(1, "v");
        assertEquals(1, ps.getParameterBinder().size());
        ps.clearParameters();
        assertEquals(0, ps.getParameterBinder().size());
    }

    @Test(expected = SQLException.class)
    public void assertPrepareStatementOnClosedConnectionThrows() throws Exception {
        conn.close();
        conn.prepareStatement("SELECT 1");
    }

    /**
     * {@code LBStatement} is deliberately no longer in this chain: a logical prepared statement
     * must satisfy {@code (CUBRIDPreparedStatement) ps} so applications migrate unmodified, and
     * Java then forbids also extending {@code LBStatement}. The shared logic arrives by composition
     * instead. What matters to callers is the vendor chain below, not which LB class supplies the
     * body.
     */
    @Test
    public void assertPreparedStatementIsAlsoStatement() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        assertTrue(ps instanceof java.sql.Statement);
        assertTrue(ps instanceof CUBRIDStatement);
        assertTrue(ps instanceof CUBRIDPreparedStatement);
    }

    @Test
    public void assertUnwrapToPreparedStatement() throws Exception {
        PreparedStatement ps = conn.prepareStatement("SELECT 1");
        assertTrue(ps.isWrapperFor(PreparedStatement.class));
        PreparedStatement unwrapped = ps.unwrap(PreparedStatement.class);
        assertNotNull(unwrapped);
    }
}
