#
#
#  Copyright 2016 CUBRID Corporation
# 
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# 
name: github-checks
on: 
  pull_request:
    branches:
      - develop
      - 'feature/**'
jobs:
  license:
    name: license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: files
        continue-on-error: true
      - name: Check license
        run: |
          set +e # make this step proceed even if a command returns non-zero
          license_headers=.github/workflows/license_headers
          result="PASS"
          for f in ${{ steps.files.outputs.added_modified }}; do
            if [ -d "$f" ]; then
              continue
            fi

            ext=$(expr $f : ".*\(\..*\)")
            case $ext in
            .java) true;; # only these formats are checked.
            *) continue ;; # skip others
            esac

            result_for_f="FAIL"
            for header in `find $license_headers -type f`; do
              line_cnt=`wc -l < $header`
              head -n $line_cnt $f | diff -w - $header 2>&1 1>/dev/null
              if [ $? -eq 0 ]; then
                result_for_f="PASS"
                break
              fi
            done

            echo "$f: $result_for_f"
            if [ "$result_for_f" = "FAIL" ]; then
              result="FAIL"
            fi
          done
          test $result = "PASS" # if non-zero, fail
  pr-style:
    name: pr-style
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[[A-Z]+-\d+\]\s.+'
  code-style:
    name: code-style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - uses: axel-op/googlejavaformat-action@v3
        with:
          skipCommit: true
          version: 1.7
          args: "--aosp --replace --set-exit-if-changed"
          files: ${{ steps.files.outputs.added_modified }}
      - name: Suggest code changes
        if: ${{ failure() }}
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: code-style (indent, googlejavaformat)
